### ISSUE TITLE
Refactor js httpclient requests into a single react client component

### ISSUE THREAD

**Issue by KennethSpeecke** [KennethSpeecke/DndRngTool#1]
**Explenation**

Every single component (eg: CharacterSheetComponent.js) that uses a client request to an api now does this by hardcoded request code.
This should be changed to a generic component that recieves URL and query parameters that then returns the given data from the api.

**Todo**

_HttpClient Component_
- [ ] Create a HttpClient Component in the front-end react application.

_Needed Component Parameters_
- [ ] Api Base Url (Root Location)
- [ ] Method type (Post, Patch, Get, Delete)

_Optional Component Parameters_
- [ ] Json object (Put, Post)
- [ ] Object Identifier (Guid)

_Refactor Request Related Code_
- [ ] Refactor all hardcoded requests with the created component.

_Pages to refactor:_
- [ ] CharacterDetails
- [ ] Characters
- [ ] Login
- [ ] Register

_Components to refactor:_
- [ ] CharacterAttackSpellCard
- [ ] CharacterCard
- [ ] CharacterInventoryCard
- [ ] CharacterProfLangCard
- [ ] CharacterRaceCard
- [ ] CharacterSheet
